my_string = input('Я живу в красивом городе, ')
print(len(my_string))
print('Я живу в красивом городе'.upper())
print('Я живу в красивом городе'.lower())
print('Я живу в красивом городе'.replace(' ', ''))
print('Я живу в красивом городе'.replace(' ', '#'))
print(my_string[0])
print(my_string[-1])
